# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluby}
  s.version = "0.7.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ale Mu\303\261oz"]
  s.date = %q{2009-12-01}
  s.default_executable = %q{fluby}
  s.description = %q{A simple command to create and compile an ActionScript project for MTASC + SWFMILL + Rake}
  s.email = %q{bomberstudios@gmail.com}
  s.executables = ["fluby"]
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "README.mdown",
     "VERSION",
     "bin/fluby",
     "lib/fluby.rb",
     "lib/templates/ASClass.as",
     "lib/templates/README",
     "lib/templates/Rakefile",
     "lib/templates/config.yml",
     "lib/templates/generators/class",
     "lib/templates/generators/delegate",
     "lib/templates/generators/xml_loader",
     "lib/templates/index.rhtml",
     "lib/templates/project.rxml",
     "lib/templates/swfobject.js"
  ]
  s.homepage = %q{http://github.com/bomberstudios/fluby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{fluby}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{MTASC + SWFMILL + Rake helper}
  s.test_files = [
    "test/helper.rb",
     "test/test_fluby.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

