#!/usr/bin/env ruby
require "rubygems"
require "fluby"

# Fluby.available_templates.each do |t|
#   p t
# end

commandline = ARGV

type = commandline.shift
name = commandline.shift
options = commandline

Fluby.generate(type,name,options)